# Generated by Django 3.0.8 on 2020-11-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0003_auto_20201110_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
