# Generated by Django 3.0.8 on 2020-11-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0004_volunteer_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='name_admin',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
