# Generated by Django 3.0.8 on 2020-11-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0005_volunteer_name_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='profile'),
        ),
    ]
