# Generated by Django 3.0.8 on 2020-12-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0007_volunteer_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, null=True)),
                ('branch', models.CharField(choices=[('EE', 'EE'), ('ECE', 'ECE'), ('CSE', 'CSE'), ('IT', 'IT'), ('ME', 'ME'), ('CE', 'CE'), ('BBA', 'BBA'), ('BCA', 'BCA'), ('MBA', 'MBA')], max_length=100)),
                ('year', models.CharField(choices=[('1st year', '1st year'), ('2nd year', '2nd year'), ('3rd year', '3rd year'), ('4th year', '4th year')], max_length=100)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('instaram', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srmgpc.TeamPost')),
            ],
        ),
    ]
