# Generated by Django 3.0.8 on 2020-12-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0008_teammembername_teampost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammembername',
            old_name='instaram',
            new_name='instagram',
        ),
    ]
