# Generated by Django 3.0.8 on 2020-12-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0009_auto_20201214_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_name', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='teammembername',
            name='cell_post',
            field=models.CharField(blank=True, choices=[('Coordinators', 'Coordinators'), ('Assistant Coordinators', 'Assistant Coordinators')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammembername',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srmgpc.Cell'),
        ),
    ]
