# Generated by Django 3.0.8 on 2020-12-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0010_auto_20201214_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembername',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srmgpc.CellName'),
        ),
        migrations.AlterField(
            model_name='teammembername',
            name='cell_post',
            field=models.CharField(blank=True, choices=[('Coordinator', 'Coordinator'), ('Assistant Coordinator', 'Assistant Coordinator')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Cell',
        ),
    ]
