# Generated by Django 3.0.8 on 2020-12-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0011_auto_20201214_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembername',
            name='cell',
            field=models.ForeignKey(blank=True, help_text='only for Coordinator Post', null=True, on_delete=django.db.models.deletion.SET_NULL, to='srmgpc.CellName'),
        ),
        migrations.AlterField(
            model_name='teammembername',
            name='cell_post',
            field=models.CharField(blank=True, choices=[('Coordinator', 'Coordinator'), ('Assistant Coordinator', 'Assistant Coordinator')], help_text='only for Coordinator Post', max_length=200, null=True),
        ),
    ]
