# Generated by Django 3.0.8 on 2020-12-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0015_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=300, null=True)),
                ('event_coordinator_no', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='where the event is done', max_length=100, null=True)),
                ('name', models.CharField(help_text='participant name', max_length=200, null=True)),
                ('winner_position', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], max_length=50, null=True)),
                ('college', models.CharField(max_length=200, null=True)),
                ('cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srmgpc.CellName')),
                ('event_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srmgpc.EventName')),
            ],
        ),
    ]
