# Generated by Django 3.0.8 on 2020-12-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0016_eventname_eventresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_detail', models.CharField(max_length=400, null=True)),
                ('update_time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
