# Generated by Django 3.0.8 on 2020-12-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0019_auto_20201219_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventname',
            name='event_coordinator_no',
        ),
    ]
