# Generated by Django 3.0.8 on 2020-12-20 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0020_remove_eventname_event_coordinator_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventname',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srmgpc.CellName'),
        ),
    ]
