# Generated by Django 3.0.8 on 2020-12-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0021_eventname_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventname',
            name='contact',
            field=models.CharField(blank=True, help_text='number of the coordinator', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventname',
            name='coordinator',
            field=models.CharField(blank=True, help_text='coordinator name for the event', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventname',
            name='place',
            field=models.CharField(blank=True, help_text='place of the event', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RulesOfEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_number', models.CharField(max_length=10, null=True)),
                ('rule', models.CharField(default='', max_length=1000, null=True)),
                ('event_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srmgpc.EventName')),
            ],
        ),
    ]
