# Generated by Django 3.0.8 on 2020-12-27 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0023_performingevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='competition_name',
        ),
        migrations.AddField(
            model_name='registration',
            name='college',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='college_rn',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='event_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srmgpc.EventName'),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='team',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='performingevent',
            name='name',
            field=models.CharField(help_text='name of performing event(in capital letter)', max_length=100, null=True),
        ),
    ]
