# Generated by Django 3.0.8 on 2020-12-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0024_auto_20201227_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srmgpc.Volunteer'),
        ),
    ]
