# Generated by Django 3.0.8 on 2020-12-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0029_auto_20201229_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
