# Generated by Django 3.0.8 on 2020-12-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0030_auto_20201229_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
