# Generated by Django 3.0.8 on 2020-12-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0032_eventname_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventname',
            name='event_date',
            field=models.DateField(),
        ),
    ]
