# Generated by Django 3.0.8 on 2022-04-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0034_auto_20220315_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, null=True)),
                ('branch', models.CharField(max_length=200, null=True)),
                ('insta', models.CharField(max_length=200, null=True)),
                ('linkedin', models.CharField(max_length=200, null=True)),
                ('github', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
