# Generated by Django 3.0.8 on 2022-04-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0035_technicalteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicalteam',
            old_name='github',
            new_name='fb',
        ),
    ]
