# Generated by Django 3.0.8 on 2022-04-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srmgpc', '0036_auto_20220404_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalteam',
            name='profile',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='tt-profile'),
        ),
    ]
